# Generated by Django 3.2.7 on 2021-09-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
